<script src="<?=$tinkermanPath?>core.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>cookie.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>dom.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>var.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>extra.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>guess.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>diff.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>BodyWrapper.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>HistoryManager.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>CommandInput.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>CommandEditor.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>Evaluator.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>Console.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItem.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>LogPanel.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>PanelManager.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>Logger.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>LogRunner.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>Box.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/Array.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/Exception.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/HTMLElement.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/Object.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/PathToObject.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/TypedObject.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/Function.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/Basic.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>logItems/Ref.js" type="text/javascript"></script>
<script src="<?=$tinkermanPath?>init.js" type="text/javascript"></script>
